### ISSUE TITLE
Add priority labels for tasks

### ISSUE THREAD

**Issue by dynnian** [d4r1us-drk/clido#1]
Tasks should have a priority level:

- Priority 1: High
- Priority 2: Medium
- Priority 3: Low
- Priority 4: None

**Comment by vhespanha** [comment]
Can you assign this one to me?

**Comment by vhespanha** [comment]
Just opened a PR, care to take a look and see if this is what you were expecting?

### [PR #2](https://github.com/d4r1us-drk/clido/pull/2)

**Comment by dynnian** [comment]
Closed by #2
