### ISSUE TITLE
Keep good separation of concerns

### ISSUE THREAD

**Issue by vhespanha** [d4r1us-drk/clido#10]
Looking at the codebase today, I noticed I've made a poor use of the Cobra library and was relying too much on the `fmt` package to write to the CLI. When I tried fixing this and using Cobra to print to stdout and stderr, I understood that the implementation of the CLI was flawed in some ways. We were "rendering" text, plumbing data, and doing logic all in the same code.

Although I don't really like MVC, since we **will** have to use it once we start the TUI, I think now would be the right time to start moving the repo in this direction. The main benefit right now would be the ability to use the method `cobra.Command.Print(f/ln)` as a general way of writing to stdout, also decoupling some logic from the printing so we can maybe share more code with the TUI when necessary.

## Benefits

- **Improved Code Organization**: Decoupling logic from printing will make the codebase cleaner and easier to maintain.
- **Consistency**: Using the `cobra.Command` type will standardize the way we write to stdout and stderr.
- **Future-Proofing**: This refactor will make it easier to share code with the TUI when we start implementing it.

## Additional Notes

- This change does not affect the user experience but will improve the maintainability of the codebase.

**Comment by dynnian** [comment]
Progress is being made for this in the develop branch. I have completed:
- [X] Use the cobra.Command type will standardize the way we write to stdout and stderr.

But this is still not done:
- [x] Decouple logic from printing to make the codebase cleaner and easier to maintain.

**Comment by dynnian** [comment]
Finally fixed by this [commit](https://github.com/d4r1us-drk/clido/commit/6c5d03faa29b6f66ed11c6c3cbd5e55bfd38ba38). Sorry to anyone who tries to review that gigantic thing. I basically touched every file in the codebase.

I'm leaving this open until a pull request to the main branch is made.
