### ISSUE TITLE
Rewrite the CLI interface using Cobra

### ISSUE THREAD

**Issue by dynnian** [d4r1us-drk/clido#4]
[Cobra](https://github.com/spf13/cobra) is a powerful library for building modern CLI applications. It offers a robust and flexible framework that simplifies the management of complex command structures and subcommands. With automatic handling of help generation, flag parsing, and command validation, Cobra allows developers to focus on the application's core functionality rather than the nuances of CLI management. Moreover, Cobra's extensibility and consistent command syntax enhance the development process, making the application more intuitive and scalable as it evolves.

**Comment by vhespanha** [comment]
Hey, I opened the PR without reading your message or this issue 😭
The PR ended up including a lot more than just cobra but it would surely close this issue
[PR #5](https://github.com/d4r1us-drk/clido/pull/5)
