### ISSUE TITLE
Error creating projects on the new version.

### ISSUE THREAD

**Issue by vhespanha** [d4r1us-drk/clido#9]
Hi!

I was testing the new code for sub-projects and sub-tasks and came across a weird error everytime I tried to create a new project. 

### The bug:
With some basic investigation I found out what was happening, once you added the new column `ParentProjectId` to the code, our SQLite instance had a schema change that wasn't migrated, so my current `~/.local/share/clido/data.db` contained the old version of that database.

### Solution:

As a solution to this, I have two things in mind.

1. Create a versioning system to the DB and a migration system, so everytime we update the schema, we include that migration on the commit, and whenever a user executes any command on a new version, the tool runs that migration before executing the command itself, fixing any schema mismatches in the process.

3. Include a `develop` branch to place the code we're still testing until we cover some use cases, then we merge to main once we hit a new minor version, (or a patch if it's related to a bug)

### Implementation
I think I can hack a simple versioning system to the DB and open a PR still today, see you later.

**Comment by dynnian** [comment]
Implementing an ORM like [gorm](https://github.com/go-gorm/gorm) would be quite helpful for this purpose

**Comment by vhespanha** [comment]
Just reverted main to HEAD^ and created the develop branch with the changes from [#7](https://github.com/d4r1us-drk/clido/issues/7)
See [#12](https://github.com/d4r1us-drk/clido/pull/12) and [#13](https://github.com/d4r1us-drk/clido/pull/13)

Next step is the [gorm](https://github.com/go-gorm/gorm) PR, merge it to develop until we release 1.1

**Comment by dynnian** [comment]
Done creating new develop branch

**Comment by vhespanha** [comment]
[#15](https://github.com/d4r1us-drk/clido/pull/15) will close this!

**Comment by dynnian** [comment]
PRs #14 and #15 have been merged, but I will leave this issue opened until it's resolved in the main branch

**Comment by dynnian** [comment]
Completed by latest PR
